# Generated by Django 4.2.2 on 2023-06-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sign_vid",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="vids/"
                    ),
                ),
            ],
        ),
    ]
